library constants;

import 'package:flutter_html/style.dart';

// Must sync with constants.js in backend
const LOOP_TITLE_TENANT_REQUEST_ACCESS = 'tenantRequestAccess';
const LOOP_TITLE_NEW_AD_WITH_IMAGE = 'newAdWithImage';
const LOOP_TITLE_NEW_AMENITY_BOOKING = 'newAmenityBooking';
const LOOP_TITLE_MANAGEMENT_NOTICE = 'managementNotice';
const LOOP_TITLE_MANAGEMENT_RECEIPT = 'managementReceipt';
// const LOOP_TITLE_AMENITY_BKG_STATUS_CHG = 'amenityBkgStatusChg';
const LOOP_TITLE_AMENITY_BOOKING_CONFIRMED = 'amenityBkgConfirmed';
const LOOP_TITLE_AMENITY_BOOKING_CANCELLED = 'amenityBkgCancelled';

const LOCAL_DB_FILENAME = 'estatemanage_tenant_sqlite.db';

// The ENC_SECRET_KEY can be generated by encrypt.Key.fromSecureRandom(32).base64
const ENC_SECRET_KEY = 'ZTqB2a/Agndf1SDCuNT9Xi69Xh5X21+E9WZb+31Gxkg=';
// The IV can be generated by encrypt.IV.fromSecureRandom(16).base64
const ENC_IV = 'dqGsLHxCE6AXsy1zZojlsg==';

// Good looking font sizes for displaying HTML markup contents
final Map<String, Style> HTML_MKUP_OPTIONS = {
  'h3': Style(fontSize: FontSize(22.0)),
  'p': Style(fontSize: FontSize(18.0)),
  'ul': Style(fontSize: FontSize(18.0))
};
